[env:atmega328p]
platform = atmelavr
board = pro16MHzatmega328
framework = arduino

upload_protocol = custom

upload_command = /usr/bin/avrdude -p m328p -c ft232h -P usb -U flash:w:$SOURCE:i -F

lib_deps =
    arduino-libraries/Servo